Blog/ViewComponents/GetArhiveViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Extensions;
using Blog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blog.ViewComponents
{
    public class GetArhiveViewComponent : ViewComponent
    {
        private readonly BlogContext _context;

		public GetArhiveViewComponent(BlogContext context)
		{
			_context = context;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			List<GetArhiveViewModel> query_arhive = await _context.Posts.OrderByDescending(y=>y.Date)
									.Select(x => new GetArhiveViewModel
									{
										Month = x.Date.ToString("MMMM"),
										MonthNum = x.Date.Month,
										Year = x.Date.Year
									}).ToListAsync();

			var arhive = query_arhive.Distinct(new GetArhiveComparer());
			return View(arhive);
		}
	}
}

Blog/ViewComponents/LastPostsViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blog.ViewComponents
{
    public class LastPostsViewComponent : ViewComponent
    {
        private readonly BlogContext _context;

		public LastPostsViewComponent(BlogContext context)
		{
			_context = context;
		}

		public async Task<IViewComponentResult> InvokeAsync(int? take)
        {

			IEnumerable<Post> lastPosts;
			if(take == null)
			{
				lastPosts = await _context.Posts.OrderByDescending(x=>x.Date).Take(5).ToListAsync();
			}
			else
			{
				lastPosts = await _context.Posts.OrderByDescending(x=>x.Date).Take(take.GetValueOrDefault()).ToListAsync();
			}
			

            return View(lastPosts);
        }
	}
}

Blog/Pages/Shared/_Layout.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/style.css" />

    <meta name="description" content="блог о странном программисте">
    <meta name="keywords" content="PHP, HTML, CSS">
</head>

<body>
    <table width="690" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF" class="main_border">
        <tr>
            <td><img src="~/images/header.jpg" width="690" height="100"></td>
        </tr>
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                        <partial name="_Left" />
                        <td valign="top">
                            <partial name="_NavMenu" />
                            @RenderBody()
                            
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td><img src="img/footer.jpg" width="690" height="20"></td>
        </tr>
    </table>
</body>
</html>

Blog/Pages/Shared/_Left.cshtml
<td width="182" valign="top" class="left">
    <div class="nav_title">Профиль</div>
    <p>
        Профиль:	<a href="page.php?id=1">Administrator</a><br>
        <br>
        <img alt='Administrator' src='avatars/1601407613.jpg' />
    </p>
    <a href='all_users.php'>Список пользователей</a>|<a href='exit.php'>Выход</a>

    <vc:list-category />

	@* Последние зпметки *@
	<vc:last-posts take="5" />

	<vc:get-arhive />
    
    <div class="nav_title">Блоги друзей</div>

    <p class='point'><img src='img/arr4.jpg' height='10' width='10'><a class='nav_link' href='http://ruseller.com' target='_blank'>Школа мастерства</a></p><p class='point'><img src='img/arr4.jpg' height='10' width='10'><a class='nav_link' href='http://photoshop-master.ru' target='_blank'>Фотошоп Уроки</a></p><p class='point'><img src='img/arr4.jpg' height='10' width='10'><a class='nav_link' href='http://ruseller-board.com' target='_blank'>Форум по этому курсу</a></p><p class='point'><img src='img/arr4.jpg' height='10' width='10'><a class='nav_link' href='http://www.phpstudent.ru' target='_blank'>Студент PHP</a></p>
    <div class="nav_title">Поиск</div>

    <form action="view_search.php" method="post" name="form_s">

        <p class="search_t">Поисковый запрос должен быть не менее 4-х символов.</p>
        <p>
            <input name="search" type="text" size="25" maxlength="40">
            <br>
            <input class="search_b" name="submit_s" type="submit" value="Искать">
        </p>


    </form>




    <p><a href="secret.php">Секретный раздел</a></p>
    <p><a href="gb.php">Гостевая</a></p>

    <div class="nav_title">Курсы валют</div>




    <div class="nav_title">Статистика</div>


    <div class="nav_title">Опрос</div>
    <br>
    <table width="$pollvars[table_width]" border="0" align="center" cellspacing="0" cellpadding="1" bgcolor="$pollvars[bgcolor_fr]">
        <tr align="center">
            <td>
                <table width="100%" border="0" cellspacing="0" cellpadding="2" align="center" bgcolor="$pollvars[bgcolor_tab]">
                    <tr valign="middle">
                        <td height="40"><font face="$pollvars[font_face]" color="$pollvars[font_color]" size="1"><b>$question</b></font></td>
                    </tr>
                    <tr align="left" valign="bottom">
                        <td>
                            <table border="0" cellspacing="0" cellpadding="1" width="100%" align="center">
                                <tr valign="top">
                                    <td>
                                        <table width="100%" border="0" cellspacing="0" cellpadding="1" align="center">
                                            <tr>
                                                <td height="22"><font face="$pollvars[font_face]" color="$pollvars[font_color]" size="1">$option_text</font></td>
                                                <td nowrap height="22"><font face="$pollvars[font_face]" color="$pollvars[font_color]" size="1"><img src="$pollvars[base_gif]/$poll_color.gif" width="$img_width" height="$pollvars[img_height]"> $vote_val</font></td>
                                            </tr>
                                            <tr>
                                                <td height="22"><font face="$pollvars[font_face]" color="$pollvars[font_color]" size="1">$option_text</font></td>
                                                <td nowrap height="22"><font face="$pollvars[font_face]" color="$pollvars[font_color]" size="1"><img src="$pollvars[base_gif]/$poll_color.gif" width="$img_width" height="$pollvars[img_height]"> $vote_val</font></td>
                                            </tr>
                                            <tr>
                                                <td height="22"><font face="$pollvars[font_face]" color="$pollvars[font_color]" size="1">$option_text</font></td>
                                                <td nowrap height="22"><font face="$pollvars[font_face]" color="$pollvars[font_color]" size="1"><img src="$pollvars[base_gif]/$poll_color.gif" width="$img_width" height="$pollvars[img_height]"> $vote_val</font></td>
                                            </tr>
                                        </table>
                                        <font face="$pollvars[font_face]" color="$pollvars[font_color]" size="1">
                                            <br>
                                            $pollvars[total_text]: <font color="#CC0000">$total_votes</font><br>
                                            $VOTE<br><br><div align="center">
                                                $COMMENT&nbsp;
                                            </div>
                                        </font>
                                    </td>
                                </tr>
                                <tr><td height="2">&nbsp;</td></tr>
                            </table>
                            <font face="$pollvars[font_face]" size="1"><a href="http://www.proxy2.de" target="_blank" title="Advanced Poll">Version $pollvars[poll_version]</a></font>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>


</td>

Blog/Pages/Shared/_NavMenu.cshtml
<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td width="25%" class="nav active">
            <p><strong><a href="/">Главная</a></strong></p>
        </td>
        <td width="25%" class="nav">
            <p><strong><a href="./subscribe.php">Рассылка</a></strong></p>
        </td>
        <td width="25%" class="nav">
            <p><strong><a href="./goodies.php">Товары</a></strong></p>
        </td>
        <td width="25%" class="nav">
            <p><strong><a href="./about.php">О нас</a></strong></p>
        </td>
    </tr>
</table>